update VocaForAllCell UI
DDD-4/Spark-iOS pull request #60
Opened 2020-08-27 12:38 UTC by Odyflame

# Description 
update VocaForAllCell UI

<div>
<img width = "200" src = "https://user-images.githubusercontent.com/44191131/91442830-68980180-e8ad-11ea-9d41-8365e713a5e4.PNG" >
</div>

2020-08-27 13:43 UTC, Haeuncs requested changes

2020-08-27 13:43 UTC, Haeuncs commented on Vocabulary/VocaForAll/VocaForAllCell.swift
> +        label.font = .BalsamiqSansBold(size: 30)
Is this the correct font setting?

2020-08-27 13:43 UTC, Haeuncs commented on Vocabulary/VocaForAll/VocaForAllCell.swift
>          label.textColor = .gray
Is this the correct color?

2020-08-27 13:43 UTC, Haeuncs commented on Vocabulary/VocaForAll/VocaForAllCell.swift
> +        imageView.layer.cornerRadius = Constant.imageRadius
Is this the correct radius?

2020-08-28 05:23 UTC, Odyflame commented
check this issue, i'll update these things.

<div>
<img width = "200" src = "https://user-images.githubusercontent.com/44191131/91524302-d722a100-e939-11ea-8406-63fafd08ce55.jpeg" >
</div>

2020-08-28 05:25 UTC, merged