[1.0.0] update 모두의단어장_2detail_1
DDD-4/Spark-iOS pull request #66
Opened 2020-08-30 08:04 UTC by Odyflame

# description
update VocaForAll UI but there's some minor issue and want some advice.

* there's problem that profile's center. 
  i fixed Arbitrarily adjusted the position. 
  (i tried 11 pro max, 11 pro, se2 and it works. but It is a temporary measure)

* the distance between cell to cell. 
The distance is farther than the design. 
Can you tell me how to reduce the cell distance?

<img width="400" alt="스크린샷 2020-08-30 오후 4 43 33" src="https://user-images.githubusercontent.com/44191131/91654027-a5980a00-eae0-11ea-8b55-37f5441abab3.png">

2020-08-30 15:30 UTC, Haeuncs requested changes
<img width="1158" alt="스크린샷 2020-08-31 오전 2 38 27" src="https://user-images.githubusercontent.com/39240556/91665775-10723100-eb33-11ea-8829-441ef0ffc8a7.png">

**important**
target 이 master 입니다 1.0.0으로 수정해주세요 👍🏻 
위에 edit 눌러서 branch 바꿔주세요

2020-08-30 15:30 UTC, Haeuncs commented on Vocabulary/VacoForAll/Detail/VocaHeaderView.swift
> +            // there are something better than this codes. i tried, but can't find better answer.
이 코드가 의미하는게 뭔지 모르겠어요.
view를 중앙정렬만 하면 안되나요?_?

2020-08-30 15:30 UTC, Haeuncs commented on Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
> +            make.top.equalTo(headerView.snp.bottom)
Constant Required
https://zpl.io/2jG3DlQ

2020-08-30 15:32 UTC, Haeuncs requested changes

2020-08-30 15:32 UTC, Haeuncs commented on Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
> +            make.top.equalTo(naviView.snp.bottom).offset(34)
I think This offset should be 24.

2020-08-30 17:24 UTC, Haeuncs commented on Vocabulary/VacoForAll/Detail/WordDetailCell.swift
> +            make.trailing.equalTo(-Constant.sideMargin)
Constant.sideMargin를 여기서 추가하지 말고
대신 UICollectionView에서 contentInset을 추가해주세요

2020-08-30 17:25 UTC, Haeuncs commented on Vocabulary/VacoForAll/Detail/WordDetailCell.swift
> +        backgroundColor = .white
shadow가 제대로 나오기 위해서 아래처럼 변경해주세요

backgroundColor = .clear
clipsToBounds = false

2020-08-30 17:42 UTC, Haeuncs commented on Vocabulary/MyVoca/MyVocaViewController.swift
>          present(wordView, animated: true, completion: nil)
change present to pushviewcontroller

2020-08-31 08:21 UTC, Odyflame commented on Vocabulary/VacoForAll/Detail/VocaHeaderView.swift
> +            // there are something better than this codes. i tried, but can't find better answer.
really great. 
make.trailing.equalTo(profileContentView) i can't think about that.

2020-08-31 08:27 UTC, Odyflame commented on Vocabulary/MyVoca/MyVocaViewController.swift
>          present(wordView, animated: true, completion: nil)
without AppDelegate change, i cant' use pushViewController because navigationController is nil.
so i change AppDelegate change like this.
` self.window?.rootViewController = UINavigationController(rootViewController: HomeViewController())`
and make HomeViewController 
`navigationController?.navigationBar.isHidden = true`

2020-08-31 09:02 UTC, merged